/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public String clickX = "X";
    public String clickO = "O";
    JLabel[] arrayJLabel = new JLabel[9];
    int matrizWinner[][] = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}, {1, 4, 7}, {2, 5, 8}, {3, 6, 9}, {1, 5, 9}, {3, 5, 7}};
    int countPlayerWinOne = 0;
    int countPlayerWinTwo = 0;
    public boolean state = true;

    public Table() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/tateti.png")));
        this.setTitle("Ta-Te-Ti");
        this.setResizable(false);
        //Initialice arrayJLabel
        arrayJLabel[0] = jL1;
        arrayJLabel[1] = jL2;
        arrayJLabel[2] = jL3;
        arrayJLabel[3] = jL4;
        arrayJLabel[4] = jL5;
        arrayJLabel[5] = jL6;
        arrayJLabel[6] = jL7;
        arrayJLabel[7] = jL8;
        arrayJLabel[8] = jL9;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jL5 = new javax.swing.JLabel();
        jL6 = new javax.swing.JLabel();
        jL7 = new javax.swing.JLabel();
        jL8 = new javax.swing.JLabel();
        jL9 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(169, 88, 78));

        jL1.setBackground(new java.awt.Color(241, 191, 115));
        jL1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL1.setForeground(new java.awt.Color(124, 57, 62));
        jL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jL1.setOpaque(true);
        jL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL1MousePressed(evt);
            }
        });

        jL2.setBackground(new java.awt.Color(241, 191, 115));
        jL2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL2.setForeground(new java.awt.Color(124, 57, 62));
        jL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL2.setOpaque(true);
        jL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL2MousePressed(evt);
            }
        });

        jL3.setBackground(new java.awt.Color(241, 191, 115));
        jL3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL3.setForeground(new java.awt.Color(124, 57, 62));
        jL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL3.setOpaque(true);
        jL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL3MousePressed(evt);
            }
        });

        jL4.setBackground(new java.awt.Color(241, 191, 115));
        jL4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL4.setForeground(new java.awt.Color(124, 57, 62));
        jL4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL4.setOpaque(true);
        jL4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL4MousePressed(evt);
            }
        });

        jL5.setBackground(new java.awt.Color(241, 191, 115));
        jL5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL5.setForeground(new java.awt.Color(124, 57, 62));
        jL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL5.setOpaque(true);
        jL5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL5MousePressed(evt);
            }
        });

        jL6.setBackground(new java.awt.Color(241, 191, 115));
        jL6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL6.setForeground(new java.awt.Color(124, 57, 62));
        jL6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL6.setOpaque(true);
        jL6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL6MousePressed(evt);
            }
        });

        jL7.setBackground(new java.awt.Color(241, 191, 115));
        jL7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL7.setForeground(new java.awt.Color(124, 57, 62));
        jL7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL7.setOpaque(true);
        jL7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL7MousePressed(evt);
            }
        });

        jL8.setBackground(new java.awt.Color(241, 191, 115));
        jL8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL8.setForeground(new java.awt.Color(124, 57, 62));
        jL8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL8.setOpaque(true);
        jL8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL8MousePressed(evt);
            }
        });

        jL9.setBackground(new java.awt.Color(241, 191, 115));
        jL9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jL9.setForeground(new java.awt.Color(124, 57, 62));
        jL9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL9.setOpaque(true);
        jL9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jL9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jL7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jL1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL8, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL9, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jL3, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL6, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL9, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
        );

        title.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(241, 191, 115));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("TA-TE-TI");

        btnClose.setBackground(new java.awt.Color(0, 0, 0));
        btnClose.setForeground(new java.awt.Color(241, 191, 115));
        btnClose.setText("Close");
        btnClose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.setForeground(new java.awt.Color(241, 191, 115));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(169, 88, 78));

        textX.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textX.setForeground(new java.awt.Color(255, 255, 255));
        textX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Team X:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Team O:");

        textO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textO.setForeground(new java.awt.Color(255, 255, 255));
        textO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textX, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(textO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(textX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textO, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addGap(2, 2, 2)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jL1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL1MousePressed
        pression(1);
    }//GEN-LAST:event_jL1MousePressed

    private void jL2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL2MousePressed
        pression(2);
    }//GEN-LAST:event_jL2MousePressed

    private void jL3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL3MousePressed
        pression(3);
    }//GEN-LAST:event_jL3MousePressed

    private void jL4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL4MousePressed
        pression(4);
    }//GEN-LAST:event_jL4MousePressed

    private void jL5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL5MousePressed
        pression(5);
    }//GEN-LAST:event_jL5MousePressed

    private void jL6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL6MousePressed
        pression(6);
    }//GEN-LAST:event_jL6MousePressed

    private void jL7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL7MousePressed
        pression(7);
    }//GEN-LAST:event_jL7MousePressed

    private void jL8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL8MousePressed
        pression(8);
    }//GEN-LAST:event_jL8MousePressed

    private void jL9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL9MousePressed
        pression(9);
    }//GEN-LAST:event_jL9MousePressed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        for (int i = 0; i < arrayJLabel.length; i++) {
            arrayJLabel[i].setText("");
            arrayJLabel[i].setBackground(new java.awt.Color(241, 191, 115));
            state = true;
        }
    }//GEN-LAST:event_btnResetActionPerformed

    /*
    If there is nothing in the box, you can press X, then it will take us to another method (changeShift();) so that if the X was pressed, the O is pressed.
     */
    public void pression(int box) {
        if (arrayJLabel[box - 1].getText().equals("") && state) {
            arrayJLabel[box - 1].setText(clickX);
            changeShift();
            checkWinner();

        }

    }

    public void showResult(boolean blocked, int count) {
        if (blocked == true) {
            String aux = String.valueOf(count);
            textX.setText(aux);
            textX.getText();
        } else {
            String aux = String.valueOf(count);
            textO.setText(aux);
            textO.getText();
        }

    }

    public void changeShift() {
        if (clickX.equals("X")) {
            clickX = clickO;
            state = true;
        } else {
            clickX = "X";
            state = true;
        }
    }


    /*
    If both the X and O matrices match then they will be painted green.
     */
    public void checkWinner() {
        for (int i = 0; i < matrizWinner.length; i++) {
            if (arrayJLabel[matrizWinner[i][0] - 1].getText().equals("X") && arrayJLabel[matrizWinner[i][1] - 1].getText().equals("X")
                    && arrayJLabel[matrizWinner[i][2] - 1].getText().equals("X")) {

                arrayJLabel[matrizWinner[i][0] - 1].setBackground(Color.GREEN);
                arrayJLabel[matrizWinner[i][1] - 1].setBackground(Color.GREEN);
                arrayJLabel[matrizWinner[i][2] - 1].setBackground(Color.GREEN);

                JOptionPane.showMessageDialog(null, "Winner Player 1 (X)");
                countPlayerWinOne++;
                state = false;
                showResult(true, countPlayerWinOne);
            } else if (arrayJLabel[matrizWinner[i][0] - 1].getText().equals("O") && arrayJLabel[matrizWinner[i][1] - 1].getText().equals("O")
                    && arrayJLabel[matrizWinner[i][2] - 1].getText().equals("O")) {

                arrayJLabel[matrizWinner[i][0] - 1].setBackground(Color.GREEN);
                arrayJLabel[matrizWinner[i][1] - 1].setBackground(Color.GREEN);
                arrayJLabel[matrizWinner[i][2] - 1].setBackground(Color.GREEN);

                JOptionPane.showMessageDialog(null, "Winner Player 2 (O)");
                countPlayerWinTwo++;
                state = false;
                showResult(false, countPlayerWinTwo);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel textO;
    private javax.swing.JLabel textX;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
